dist: bionic

language: python

python:
  - "3.6"
  - "3.7"

before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - sudo sh -c "echo 'deb [trusted=yes] http://downloads.skewed.de/apt/bionic xenial universe' >> /etc/apt/sources.list"
  - sudo sh -c "echo 'deb-src [trusted=yes] http://downloads.skewed.de/apt/bionic xenial universe' >> /etc/apt/sources.list"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7A80C8ED4FCCBE09
  #- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install g++-4.9
  - sudo apt-get install python3-graph-tool

install:
  - CC=gcc-4.9 CXX=g++-4.9 python setup.py build_ext
  - pip install .
  - pip install mock==3.0.*
  - pip install sphinx==1.7.5
  - pip install sphinx_rtd_theme==0.4.*
  - pip install -r requirements.txt
  - pip install -r requirements_optional.txt

script:
  - py.test --cov=./ --cov-config=.coveragerc

after_success:
  - coveralls
