name: publish_conda

on:
  #release:
  #  types: [published]
  workflow_dispatch: # on demand
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        conda config --append channels conda-forge
        conda config --append channels giuliorossetti
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: GiulioRossetti/conda-package-publish-action@cdlib_a
      with:
        subdir: 'conda'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: 'linux-32'
        override: true
        # dry_run: true
